### ISSUE TITLE
Remove cognitoidentityprovider dependency?

### ISSUE THREAD

**Issue by dacz** [AlexRudd/cognito-srp#4]
What is the reason to keep dependency to aws sdk cognito provider? I see it in the code only once as referencing type `RespondToAuthChallengeInput`. It's not used in your tests, too.

Base aws is used just to make string ref - aws.String. This may be replaced by by ref to string.

My rationale: I'm building CLI app that uses your library to auth without need to construct cip client, just user credentials, same like web app. It's quite a big dep.

I'm golang novice so maybe I'm wrong about the need of having this.

**Comment by alexrudd** [comment]
Hey @dacz,

You're right, there isn't a need for this package to expose the internals of `aws-sdk-go-v2`, and this does limit the flexibility of the package. I coupled it closely to those aws packages because I didn't expect it to be used in any other way and that was the only problem I was trying to solve at the time.

Unfortunately fixing this would mean changing the public API of the package. I have been meaning to release this repo as a go module, so perhaps the best approach would be to release it as it currently is as v1 and then remove the aws dependency and release that as v2.

I'll try and look into this during the week. Thanks!

**Comment by alexrudd** [comment]
Hey, please look at branch v2 for the fixed API. If you set your dependencies to be `github.com/alexrudd/cognito-srp/v2` you should pull down the release from that branch.

Let me know how it goes :)

**Comment by dacz** [comment]
Hi Alex,

thanks. My fork: https://github.com/dacz/cognitoclientgo/blob/master/srp/srp.go made just the smallest changes to replace the aws types.

Your new PasswordVerifierChallenge returns diffrent object. Why did you change this?

Thanks,
David

**Comment by alexrudd** [comment]
In your fork you copied aws's [RespondToAuthChallengeInput](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider#RespondToAuthChallengeInput) struct into your [cognito-srp library](https://github.com/dacz/cognitoclientgo/blob/master/srp/srp.go#L138). This might seem like an easy solution, but your copied type will not be useful to the caller of `PasswordVerifierChallenge()` - the returned `RespondToAuthChallengeInput` would cause a compilation error if passed to [RespondToAuthChallengeRequest()](https://godoc.org/github.com/aws/aws-sdk-go-v2/service/cognitoidentityprovider#CognitoIdentityProvider.RespondToAuthChallengeRequest), as it's not the required type for that function definition.

Returning just the map is more flexible and doesn't make assumptions about how the importer will use the package.

**Comment by dacz** [comment]
I definitely agree that map is more flexible. I do not use RespondToAuthChallenge via aws client but as serialized json within post call, it works for me. But this is definitely not an argument to keep it that way :) I suppose that this is the reason why you return now just the response, right?

May I ask: why wouldn't be possible to make type casting from the copied struct to sdk struct? I tried casting similar struct: https://play.golang.org/p/y_hiiFmtCgu and it works. 

I'm golang beginner, please excuse me for such trivial questions.

**Comment by alexrudd** [comment]
Yeah the `ChallengeResponses` is the only part of `RespondToAuthChallengeInput` that this library is truly concerned with. You're right that casting would work, but then you have to maintain an exact copy of aws's struct in your own code; and if aws decide to change that struct by adding an additional field, then the cast [will fail](https://play.golang.org/p/np2oXfkxpYL).

Questions are welcome :)

**Comment by dacz** [comment]
You're right. I have a feeling that even srp package and my cognito login package are little bit in the shadow zone of nearly reverse engineering of something that should be provided by AWS itself - so it's all a little bit fragile :)

**Comment by alexrudd** [comment]
Best way to learn. Thanks for creating the issue!
